name: publish to nuget

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ["3.1.x"]
        
    steps:
      - uses: actions/checkout@v2

      - name: setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{matrix.dotnet-version}}
      
      # Test
      - name: run tests
        run: dotnet test --filter Ajuna.NetApi.Test --no-build --verbosity normal

      # Publish
      - name: publish on version change
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: Ajuna.NetApi/Ajuna.NetApi.csproj
          # NuGet package id, used for version detection & defaults to project name
          PACKAGE_NAME: Ajuna.NetApi
          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
